### PR TITLE
Flag to Skip Pyang Errors in Model Files

### PR DESCRIPTION
**Pull request by jhanm12**
Flag to Skip Pyang Errors in Model Files

Test Logs:

```
Writing yangkit-models-cisco-ios-xr-24.2.1/setup.cfg
creating dist
Creating tar archive
removing 'yangkit-models-cisco-ios-xr-24.2.1' (and everything under it)

Successfully created source distribution

=================================================
Successfully generated Python Yangkit cisco-ios-xr bundle package at /auto/cafy/Yang/out
Please refer to the README for information on how to install the package in your environment

Code generation completed successfully!  Manual installation required!

Total time taken: 7 minutes 45 seconds

(yangkit_venv) [jhanm@sjc-ads-1025 api_generator]$ 
```

### CODE REVIEW

**Comment by jhanm12** [comment]
Command : 
```
./generate.py --bundle /auto/cafy/Yang/bundle.json --output-directory /auto/cafy/Yang/out -v -i
```

**Comment by jhanm12** [comment]
Added an additional "-i" flag for this purpose.

**Comment by akshansh237** [comment]
Add UT for the case being handled here

**Comment by jhanm12** [comment]
Complete UT Logs: /ws/jhanm-sjc/skip_pyang.logs

**Comment by akshansh237** [comment]
> /ws/jhanm-sjc/skip_pyang.logs

it would be great if you can dump what models were skipped and why at the end or at least notify the user that some of them were skipped. otherwise the user wont know if it happened

**Comment by nishantupadhyay123** [comment]
do we have test logs here Jhansi ?

**Comment by jhanm12** [comment]
Display the Skipped Modules/Pyang Errors - At the end, to notify the users. (If the Skip Pyang Errors Flag is Enabled.)

https://github.com/yang-infra/yangkit/pull/18/commits/3550fccc456a520e888769de2c88c85ac5412f8f

Test Logs: /ws/jhanm-sjc/warning_pyang_logs.txt

**Review by akshansh237 — APPROVED** [review]

**Pull request merged**
